Fixed cmdLslah, cmdPwrSens, and cmdCksum to follow proper design guidelines

diff --git a/cmds/cmdLslah b/cmds/cmdLslah
--- a/cmds/cmdLslah
+++ b/cmds/cmdLslah
@@ -1,4 +1,68 @@
 #!/bin/sh
 # I like using ls -lah sometimes. unnecessary? maybe. did I do it anyway? yes
-ls -lah $1 > /var/log/lslah.output echo "Output in /var/log/lslah.output"
-exit 0
+
+instdir=$(cd $(dirname $0); pwd) 
+. ${instdir}/log.sh 
+log_init $0 
+
+ls -lah $1 > /var/log/lslah.output 
+echo "Output in /var/log/lslah.output" exit 0
+
+# heres the usage description
+usage() {
+	echo "Lslah {path}"
+	echo "runs 'ls -lah {path}'"
+}
+
+# gets the options to determine if usage should be printed
+O=`getopt h "$@"` || exit 1 
+eval set -- "$O" 
+while true; do
+	case "$1" in
+		-h)
+			usage
+			exit 0
+			;;
+		--)
+			shift
+			break;
+			;;
+		*)
+			log "[E] unknown arg: $1)"
+			exit 1
+			;;
+	esac 
+done
+
+
+# shift the args beyond the getopt options
+shift "$((OPTIND-1))" 
+
+path=$1
+
+#
+# Validate input
+#
+# yes I know, technically ls -lah doesn't need a path. But there's no cd, so you have to
+# give this a path since there's little point in a default
+if [ -z "$path" ] 
+	then
+	log "[E] Need to specify path"
+	exit 1
+fi
+
+#
+# Execute ls command, intercepting the output so we can filter it
+#
+ls -lah $path > $path/.Lslah.output
+
+exitStatus=$? 
+if [ $exitStatus -eq 0 ] 
+	then
+	echo "ls -lah $path" 
+	echo "See the output in $path/Lslah.output"
+else
+	log "[E] lslah error: $1" 
+fi
+
+exit $exitStatus
diff --git a/cmds/cmdPwrSens b/cmds/cmdPwrSens
--- a/cmds/cmdPwrSens
+++ b/cmds/cmdPwrSens
@@ -1,4 +1,59 @@
 #!/bin/sh
+# In the absense of a clearly explained telemetry database, this exist
+
+instdir=$(cd $(dirname $0); pwd)
+. ${instdir}/log.sh
+log_init $0
+
+#
+usage() {
+	echo "PwrSens [-n]"
+	echo "-n removes old output"
+}
+
+removePreviousOutput() {
+	rm /var/log/cmdPwrSens.output
+}
+
+O=`getopt h "$@"` || exit 1
+eval set -- "$O"
+while true; do
+	case "$1" in
+ 	-h) 
+		usage
+ 		exit 0
+ 		;;
+	-n)
+		removePreviousOutput
+		break;
+		;;
+	--)
+ 		shift
+		break;
+		;;
+	*)
+ 		log "[E] unknown arg:  $1)"
+		exit 1
+		;;    
+	esac
+done
+
+#
+# Execute sys-status command, intercepting the output so we can filter it
+#
+sys-status >> /var/log/cmdPwrSens.output
+
+exitStatus=$?
+
+if [ $exitStatus -eq 0 ] 
+	then
+	echo "Success: Find output in /var/log/cmdPwrSens.output"
+else
+	log "[E] sys-status error"
+fi
+
+exit $exitStatus
+
 sys-status | grep PwrSens >> /var/log/PwrSens.output echo "Output at 
 /var/log/PwrSens.output"
 exit 0
